SakhCuba/Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SakhCuba.Models
{
    public class News
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string FirstColumn { get; set; }
        public string SecondColumn { get; set; }
        public string ThirdColumn { get; set; }

        public Images Image { get; set; }
    }
}

SakhCuba/Models/NewsViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SakhCuba.Models
{
    public class NewsViewModel
    {
        public string Id { get; set; }
        public string Header { get; set; }
        public string FirstColumn { get; set; }
        public string SecondColumn { get; set; }
        public string ThirdColumn { get; set; }
        public IFormFile Picture { get; set; }
    }
}

SakhCuba/Areas/Admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SakhCuba.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace SakhCuba.Areas.Admin.Controllers
{
    
    [Area("Admin")]
    [Authorize]
    public class NewsController : Controller
    {
        private readonly SakhCubaContext _context;
        private readonly IWebHostEnvironment _env;

        public NewsController(SakhCubaContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        // GET: Admin/News
        [Route("[area]/[controller]")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.News.ToListAsync());
        }

        // GET: Admin/News/Details/5
        [Route("[area]/[controller]/Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .FirstOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // GET: Admin/News/Create
        [Route("[area]/[controller]/Create")]

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[area]/[controller]/[action]")]
        public async Task<IActionResult> Create(NewsViewModel newsViewModel)
        {
            if (ModelState.IsValid)
            {
                News news = new News
                {
                    Header = newsViewModel.Header,
                    FirstColumn = newsViewModel.FirstColumn,
                    SecondColumn = newsViewModel.SecondColumn,
                    ThirdColumn = newsViewModel.ThirdColumn,
                    Picture = ImageConvertion(newsViewModel.Picture)
                };
                _context.News.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(newsViewModel);
        }

        // GET: Admin/News/Edit/5
        [Route("[area]/[controller]/Edit")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            News news = await _context.News.FindAsync(id);
            NewsEditViewModel n = new NewsEditViewModel
            {
                Id = news.Id.ToString(),
                Header = news.Header,
                FirstColumn = news.FirstColumn,
                SecondColumn = news.SecondColumn,
                ThirdColumn = news.ThirdColumn,
                Picture = news.Picture
            };

            return View(n);
        }

        // POST: Admin/News/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("[area]/[controller]/[action]")]
        public async Task<IActionResult> Edit(NewsEditViewModel news)
        {
            if (ModelState.IsValid)
            {
                News n = new News
                {
                    Id = int.Parse(news.Id),
                    Header = news.Header,
                    FirstColumn = news.FirstColumn,
                    SecondColumn = news.SecondColumn,
                    ThirdColumn = news.ThirdColumn
                };

                try
                {
                    if (news.NewPicture != null)
                    {
                        n.Picture = ImageConvertion(news.NewPicture);
                        _context.News.Update(n);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        _context.News.Attach(n);
                        _context.Entry(n).Property(x => x.Picture).IsModified = false;
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(n.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(news);
        }

        // GET: Admin/News/Delete/5
        [HttpGet]
        [Route("[area]/[controller]/[action]")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.FirstOrDefaultAsync(m => m.Id == id);

            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        // POST: Admin/News/Delete/5
        [HttpPost]
        [Route("[area]/[controller]/[action]")]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if(id != null)
            {
                News news = new News { Id = id.Value };
                _context.Entry(news).State = EntityState.Deleted;
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return NotFound();
        }

        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.Id == id);
        }

        private byte[] ImageConvertion(IFormFile image)
        {
            if (image != null)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(image.OpenReadStream()))
                {
                    imageData = binaryReader.ReadBytes((int)image.Length);
                }
                return imageData;
            }
            return null;
        }
    }
}

SakhCuba/Areas/Admin/Views/News/Create.cshtml
@model SakhCuba.Models.NewsViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Header" class="control-label"></label>
                <input asp-for="Header" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstColumn" class="control-label"></label>
                <input asp-for="FirstColumn" class="form-control" value="" />
                <span asp-validation-for="FirstColumn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondColumn" class="control-label"></label>
                <input asp-for="SecondColumn" class="form-control" value="" />
                <span asp-validation-for="SecondColumn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThirdColumn" class="control-label"></label>
                <input asp-for="ThirdColumn" class="form-control" value="" />
                <span asp-validation-for="ThirdColumn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Picture" class="control-label"></label>
                <div>
                    <input asp-for="Picture" type="file" id="customFile" />
                </div>
                <span asp-validation-for="Picture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SakhCuba/Areas/Admin/Views/News/Delete.cshtml
@model SakhCuba.Models.News

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Header)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstColumn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstColumn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondColumn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondColumn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ThirdColumn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ThirdColumn)
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd>
            @if (Model.Picture != null)
            {
                <img src="data:image/png;base64,@(Convert.ToBase64String(Model.Picture))" style="height:50%; width:50%" />
            }
        </dd>
    </dl>
    <form asp-action="DeleteConfirmed" asp-controller="News">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SakhCuba/Areas/Admin/Views/News/Details.cshtml
@model SakhCuba.Models.News

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>News</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Header)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Header)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstColumn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstColumn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SecondColumn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SecondColumn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ThirdColumn)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ThirdColumn)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Picture)
        </dt>
        <dd>
            @if (Model.Picture != null)
            {
                <img src="data:image/png;base64,@(Convert.ToBase64String(Model.Picture))" style="height:50%; width:50%" />
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SakhCuba/Areas/Admin/Views/News/Edit.cshtml
@model SakhCuba.Models.NewsEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Header" class="control-label"></label>
                <label class="control-label">Старое: @Model.Header</label>
                <input asp-for="Header" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstColumn" class="control-label"></label>
                <label class="control-label">Старое: @Model.FirstColumn</label>
                <input asp-for="FirstColumn" class="form-control" />
                <span asp-validation-for="FirstColumn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondColumn" class="control-label"></label>
                <label class="control-label">Старое: @Model.SecondColumn</label>
                <input asp-for="SecondColumn" class="form-control" />
                <span asp-validation-for="SecondColumn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThirdColumn" class="control-label"></label>
                <label class="control-label">Старое: @Model.ThirdColumn</label>
                <input asp-for="ThirdColumn" class="form-control" />
                <span asp-validation-for="ThirdColumn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Старая картинка</label>
                @if (Model.Picture != null)
                {
                    <img src="data:image/png;base64,@(Convert.ToBase64String(Model.Picture))" style="height:50%; width:50%" />
                }
            </div>
            <div class="form-group">
                <label asp-for="NewPicture" class="control-label"></label>
                <div>
                    <input asp-for="NewPicture" type="file" id="customFile" />
                </div>
                <span asp-validation-for="NewPicture" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SakhCuba/Areas/Admin/Views/News/Index.cshtml
@model IEnumerable<SakhCuba.Models.News>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Header)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstColumn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondColumn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThirdColumn)
            </th>
            <th>
                Картинка
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Header)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstColumn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondColumn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThirdColumn)
            </td>
            <td>
                @if (item.Picture != null)
                {
                    <img src="data:image/png;base64,@(Convert.ToBase64String(item.Picture))" height="100px" width="100px" />
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>